language: objective-c
before_script: export LANG=en_US.UTF-8
before_install: gem install cocoapods -v '0.33.1'
script: ./scripts/cli/bin/cli build --cli
notifications:
  email:
    recipients:
      - travis@segment.io
    on_success: always
    on_failure: always
